"use client";

/**
 * SourceTooltip - Data Lineage Indicator
 * Explains where field data comes from using semantic colors:
 * - Blue: Extracted from PDF
 * - Purple: AI/Template generated
 * - Green: Mapped to export target
 */

import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from "@/components/ui/tooltip";
import { FileText, Sparkles, CheckCircle2 } from "lucide-react";
import { cn } from "@/lib/utils";

export type SourceType = 'extracted' | 'computed';
export type LogicType = 'none' | 'template' | 'ai_enrichment';

interface SourceTooltipProps {
    sourceType: SourceType;
    logicType?: LogicType;
    isMapped?: boolean;
    targetSystem?: string;
    children: React.ReactNode;
    className?: string;
}

export function SourceTooltip({
    sourceType,
    logicType = 'none',
    isMapped = false,
    targetSystem,
    children,
    className,
}: SourceTooltipProps) {
    const isVirtual = sourceType === 'computed';
    const isAI = logicType === 'ai_enrichment';
    const isTemplate = logicType === 'template';

    return (
        <TooltipProvider>
            <Tooltip>
                <TooltipTrigger asChild>
                    <span className={cn("inline-flex", className)}>
                        {children}
                    </span>
                </TooltipTrigger>
                <TooltipContent side="top" className="max-w-xs">
                    <div className="space-y-1.5 text-xs">
                        {/* Source indicator */}
                        <div className="flex items-center gap-2">
                            {isVirtual ? (
                                <>
                                    <Sparkles className="h-3.5 w-3.5 text-[var(--color-source-virtual)]" />
                                    <span>
                                        {isAI ? "Generated by AI" : isTemplate ? "Generated from Template" : "Computed Field"}
                                    </span>
                                </>
                            ) : (
                                <>
                                    <FileText className="h-3.5 w-3.5 text-[var(--color-source-extracted)]" />
                                    <span>Found in PDF</span>
                                </>
                            )}
                        </div>
                        
                        {/* Mapping status */}
                        {isMapped && (
                            <div className="flex items-center gap-2 text-[var(--color-status-mapped)]">
                                <CheckCircle2 className="h-3.5 w-3.5" />
                                <span>Ready for {targetSystem || "Export"}</span>
                            </div>
                        )}
                    </div>
                </TooltipContent>
            </Tooltip>
        </TooltipProvider>
    );
}

/** Legend component for displaying in grid headers or info areas */
interface SourceLegendProps {
    className?: string;
    compact?: boolean;
}

export function SourceLegend({ className, compact = false }: SourceLegendProps) {
    const items = [
        { 
            badge: "S", 
            label: "Source", 
            description: "Extracted from PDF",
            badgeClass: "bg-blue-100 dark:bg-blue-900/80 text-blue-600 dark:text-blue-400"
        },
        { 
            badge: "V", 
            label: "Virtual", 
            description: "AI/Template",
            badgeClass: "bg-purple-100 dark:bg-purple-900/80 text-purple-600 dark:text-purple-400"
        },
        { 
            badge: "⚠", 
            label: "Unmapped", 
            description: "Not in export",
            badgeClass: "bg-amber-100 dark:bg-amber-900/80 text-amber-600 dark:text-amber-400"
        },
    ];

    if (compact) {
        return (
            <div className={cn("flex items-center gap-3 text-xs text-muted-foreground", className)}>
                {items.map(item => (
                    <span key={item.label} className="flex items-center gap-1.5">
                        <span className={cn("text-[10px] px-1.5 py-0.5 rounded font-semibold", item.badgeClass)}>
                            {item.badge}
                        </span>
                        {item.label}
                    </span>
                ))}
            </div>
        );
    }

    return (
        <div className={cn("flex items-center gap-4 text-xs text-muted-foreground", className)}>
            {items.map(item => (
                <span key={item.label} className="flex items-center gap-1.5">
                    <span className={cn("text-[10px] px-1.5 py-0.5 rounded font-semibold", item.badgeClass)}>
                        {item.badge}
                    </span>
                    <span className="font-medium">{item.label}</span>
                    <span className="text-muted-foreground/70">({item.description})</span>
                </span>
            ))}
        </div>
    );
}
